URL="https://cdimage.ubuntu.com/ubuntustudio/releases/REPLACE_VERSION/release/ubuntustudio-REPLACE_VERSION-dvd-amd64.iso.torrent"
TYPE=torrent
CONTENTS="\
casper/vmlinuz|vmlinuz
casper/initrd|initrd
casper/filesystem.squashfs|filesystem.squashfs"
EXTRACT_INITRD="true"
INITRD_NAME="initrd"
INITRD_TYPE="zstd"
